In [1]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(i[-5 :-2])

[40 50 60]


In [2]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(i[-3 :-1])

[60 70]


In [3]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(i[2 :-3])

[30 40 50]


In [4]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(i[0:4:2])

[10 30]


In [5]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(i[0:7:3])

[10 40 70]


In [6]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(i[::])

[10 20 30 40 50 60 70 80]


In [7]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(i[ : : 2 ])

[10 30 50 70]


In [8]:
import numpy as np
i = np.array([
[10, 20, 30, 40, 50], 
[60, 70, 80, 90, 100] 
])
print(i[1, 0:3])

[60 70 80]


In [9]:
import numpy as np
i = np.array([
  [10, 20, 30, 40, 50], 
  [60, 70, 80, 90, 100] 
  ])
print(i[0, 1:4])

[20 30 40]


In [10]:
import numpy as np
i = np.array([
  [10, 20, 30, 40, 50], 
  [60, 70, 80, 90, 100], 
  [11, 22, 33, 44, 55] 
  ])
print(i[2, 2:4])

[33 44]


In [11]:
import numpy as np
i = np.array([
[10, 20, 30, 40, 50], 
[60, 70, 80, 90, 100], 
[11, 22, 33, 44, 55] 
 ])
print(i[0:2, 1])

[20 70]


In [12]:
import numpy as np
i = np.array([
[10, 20, 30, 40, 50], 
[60, 70, 80, 90, 100], 
[11, 22, 33, 44, 55], 
[1, 2, 3, 4, 5] 
])
print(i[0:4, 0:2])

[[10 20]
 [60 70]
 [11 22]
 [ 1  2]]


In [13]:
import numpy as np
i = np.array([
[10, 20, 30, 40, 50], 
[60, 70, 80, 90, 100], 
[11, 22, 33, 44, 55], 
[1, 2, 3, 4, 5] 
 ])
print(i[0:3, -3:-1])

[[30 40]
 [80 90]
 [33 44]]


In [15]:
import numpy as np
i = np.array([10, 20, 30, 40, 50])
print(i.dtype)

int32


In [19]:
import numpy as np
i = np.array([10.10, 20.20, 30.30])
i1 = i.astype('i')
print(i1)
print(i1.dtype)
print(i)

[10 20 30]
int32
[10.1 20.2 30.3]


In [20]:
import numpy as np
i = np.array([10, 20, 30])
i1 = i.astype('f')
print(i1)
print(i1.dtype)

[10. 20. 30.]
float32


In [22]:
import numpy as np
i = np.array([10.10, 0, 30, 5, 23.25, 0, 0])
i1 = i.astype(bool)
print(i1)
print(i1.dtype)

[ True False  True  True  True False False]
bool
